### ISSUE TITLE
PayPalEnvironment and PayPalIntegrationType Missing

### ISSUE THREAD

**Issue by aadilali** [Enngage/ngx-paypal#43]
Hi,
I was trying to install and use ngx-paypal but receive following error on Angular 7
PayPalEnvironment and PayPalIntegrationType missing in ngx-paypal. Version 4.0.2 is worknig fine but i need paypal button and Pay with Credit Card jsut like your demo site. But in 4.0.2 I can only see paypal button. Could you please provide some documentation??

**Comment by Enngage** [comment]
Hi, sure - can you take a look at the other branch? https://github.com/Enngage/ngx-paypal/tree/sdk-migration 

I wanted to merge this, but I might be doing some more changes until then. I published it as latest so that people can test it out and let me know what doesnt work :)

**Comment by botoxparty** [comment]
I tried building from the other branch and I still get pretty much the same error:

`ERROR TypeError: Cannot read property 'ClientSideREST' of undefined`

**Comment by Enngage** [comment]
ClientSideREST is no longer exported, there is no need to distinguish server side & client site integration with new PayPal sdk.
